# Generated by Django 6.0.3 on 2026-04-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_maktab_tur'),
    ]

    operations = [
        migrations.AddField(
            model_name='tekshiruv',
            name='geo_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tekshiruv',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tekshiruv',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
