# Generated by Django 6.0.3 on 2026-04-22 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tekshiruv_geo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dastur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('tavsif', models.TextField(blank=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dastur',
                'verbose_name_plural': 'Dasturlar',
                'ordering': ['-yaratilgan_vaqt'],
            },
        ),
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('ha_yoq', "Ha/Yo'q"), ('shkala_1_5', 'Shkala 1-5'), ('variant', 'Variant tanlash'), ('son', 'Son kiritish'), ('foto', 'Foto'), ('matn', 'Matn')], max_length=20)),
                ('matn', models.TextField()),
                ('variantlar', models.JSONField(blank=True, null=True)),
                ('majburiy', models.BooleanField(default=True)),
                ('foto_biriktirish', models.BooleanField(default=False)),
                ('tartib', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['tartib', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Javob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiymat', models.JSONField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='javoblar/')),
                ('tekshiruv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='javoblar', to='app.tekshiruv')),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='javoblar', to='app.savol')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
            },
        ),
        migrations.CreateModel(
            name='Sorovnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tavsif', models.TextField(blank=True)),
                ('nashr_holati', models.CharField(choices=[('qoralama', 'Qoralama'), ('nashr', 'Nashr etilgan'), ('arxiv', 'Arxiv')], default='qoralama', max_length=20)),
                ('ortacha_vaqt_min', models.IntegerField(default=5)),
                ('dastur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sorovnoma', to='app.dastur')),
            ],
            options={
                'verbose_name': "So'rovnoma",
                'verbose_name_plural': "So'rovnomalar",
            },
        ),
        migrations.AddField(
            model_name='savol',
            name='sorovnoma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='app.sorovnoma'),
        ),
        migrations.CreateModel(
            name='Tadbir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('muddat', models.CharField(blank=True, max_length=100)),
                ('masul', models.CharField(blank=True, max_length=200)),
                ('tartib', models.IntegerField(default=0)),
                ('dastur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tadbirlar', to='app.dastur')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['tartib', 'id'],
            },
        ),
        migrations.AddField(
            model_name='savol',
            name='tadbir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savollar', to='app.tadbir'),
        ),
        migrations.CreateModel(
            name='Topshiriq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maktab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topshiriqlar', to='app.maktab')),
                ('sorovnoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topshiriqlar', to='app.sorovnoma')),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'unique_together': {('sorovnoma', 'maktab')},
            },
        ),
    ]
