# Generated by Django 6.0.3 on 2026-04-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sorovnoma_modellar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tekshiruv',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tekshiruvlar/video/'),
        ),
    ]
