# Generated by Django 6.0.5 on 2026-05-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_video_field_tekshiruv'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['murojaat', '-vaqt'], name='app_comment_murojaa_7ad9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['telegram_user_id'], name='app_comment_telegra_bddb54_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['murojaat'], name='app_like_murojaa_0aaf59_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['telegram_user_id'], name='app_like_telegra_4224b3_idx'),
        ),
        migrations.AddIndex(
            model_name='maktab',
            index=models.Index(fields=['viloyat'], name='app_maktab_viloyat_0f155a_idx'),
        ),
        migrations.AddIndex(
            model_name='maktab',
            index=models.Index(fields=['tur'], name='app_maktab_tur_a33945_idx'),
        ),
        migrations.AddIndex(
            model_name='maktab',
            index=models.Index(fields=['holat'], name='app_maktab_holat_0172f5_idx'),
        ),
        migrations.AddIndex(
            model_name='murojaat',
            index=models.Index(fields=['-yuborilgan_vaqt'], name='app_murojaa_yuboril_1efed5_idx'),
        ),
        migrations.AddIndex(
            model_name='murojaat',
            index=models.Index(fields=['viloyat', '-yuborilgan_vaqt'], name='app_murojaa_viloyat_fa8f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='murojaat',
            index=models.Index(fields=['telegram_user_id'], name='app_murojaa_telegra_bd72c6_idx'),
        ),
        migrations.AddIndex(
            model_name='murojaat',
            index=models.Index(fields=['holat'], name='app_murojaa_holat_cdf183_idx'),
        ),
        migrations.AddIndex(
            model_name='murojaat',
            index=models.Index(fields=['infratuzilma'], name='app_murojaa_infratu_585af1_idx'),
        ),
        migrations.AddIndex(
            model_name='tekshiruv',
            index=models.Index(fields=['maktab', '-vaqt'], name='app_tekshir_maktab__72b96c_idx'),
        ),
        migrations.AddIndex(
            model_name='tekshiruv',
            index=models.Index(fields=['telegram_user_id'], name='app_tekshir_telegra_ce0ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='tekshiruv',
            index=models.Index(fields=['natija'], name='app_tekshir_natija_e3e3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='tekshiruv',
            index=models.Index(fields=['geo_valid'], name='app_tekshir_geo_val_292757_idx'),
        ),
    ]
